spring:
  application:
    name: currency-service
  zipkin:
    base-url: http://localhost:9411
    enabled: true
    sender:
      type: web
  sleuth:
    sampler:
      percentage: 1.0

sample:
  zipkin:
    enabled: true

eureka:
  client:
    service-url:
      default-zone: ${EUREKA_URI:http://localhost:8761/eureka}
server:
  port: 8082