version: '3.5'
services:

  eureka-server:
    build: ./eureka-server
    ports:
      - 8761:8761

  zuul-gateway:
    build: ./zuul-gateway
    depends_on:
      - eureka-server
    ports:
      - 9999:9999

  currency-service:
    build: ./currency-service
    depends_on:
      - eureka-server
      - zuul-gateway
    ports:
      - "8082-8083:8082"

#Add second instance in docker compose
#after docker-compose up
#docker-compose scale currency-service=2

  currency-service-loadbalancer:
    build: ./currency-service-loadbalancer
    depends_on:
      - eureka-server
      - zuul-gateway
    ports:
      - 5555:5555

#Zipkin
# docker run -d -p 9411:9411 openzipkin/zipkin
# Run
# java -jar zipkin.jar
