spring:
  application:
    name: CurrencyAPIGateway
  zipkin:
    base-url: http://localhost:9411
    enabled: true
    sender:
      type: web
  sleuth:
    sampler:
      percentage: 1.0

sample:
  zipkin:
    enabled: true

server:
  port: 9999

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
    healthcheck:
      enabled: true

zuul:
  routes:
    currency-service-loadbalancer:
      path: /lb/**
      service-id: currency-service-loadbalancer
  health:
    enabled: true

