spring:
  application:
    name: CurrencyAPIGateway
server:
  port: 9999
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
zuul:
  routes:
    currency-service-loadbalancer:
      path: /lb/**
      service-id: currency-service-loadbalancer
  health:
    enabled: true