spring:
  application:
    name: currency-service-loadbalancer
  zipkin:
    base-url: http://localhost:9411
    enabled: true
    sender:
      type: web
  sleuth:
    sampler:
      percentage: 1.0

sample:
  zipkin:
    enabled: true

server:
  port: 5555

currency-service:
  ribbon:
    listOfServers: localhost:8082,localhost:8083
    eureka:
      enabled: true

eureka:
  client:
    service-url:
      default-zone: ${EUREKA_URI:http://localhost:8761/eureka}
    healthcheck:
      enabled: true
  instance:
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2
    metadata-map:
      instanceId: ${spring.application.name}:${random.value}

feign:
  hystrix:
    enabled: true
