spring:
  application:
    name: currency-service-loadbalancer

server:
  port: 5555

currency-service:
  ribbon:
    listOfServers: http://localhost:8082,http://localhost:8083

eureka:
  client:
    service-url:
      default-zone: ${EUREKA_URI:http://localhost:8761/eureka}
    healthcheck:
      enabled: true
  instance:
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2
    metadata-map:
      instanceId: ${spring.application.name}:${random.value}
    prefer-ip-address: true

